name: Build and Deploy

on:
  push:
    branches: [ main, master ]  # Include both common branch names
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Remove the cache option since we don't have a lock file yet
      
      - name: Generate lock file if missing
        run: |
          if [ ! -f "package-lock.json" ] && [ ! -f "yarn.lock" ]; then
            echo "No lock file found. Generating package-lock.json..."
            npm i --package-lock-only
          fi

      - name: Install dependencies
        # Use ci if there's a lock file, otherwise use install
        run: npm ci || npm install
        
      - name: Build
        run: npm run build
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
